[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [
    "netlify/functions/content.html"
  ]

[[redirects]]
  from = "/netlify/*"
  to = "/404.html"
  status = 404
  force = true

[[headers]]
  for = "/netlify/*"
  [headers.values]
  X-Robots-Tag = "noindex, nofollow, noarchive"
